# This is a basic workflow to help you get started with Actions

name: wf-A

# Controls when the workflow will run
on:
  workflow_dispatch:
permissions:
  actions: read
  contents: write
  issues: write
jobs:
  trigger-build-github:
    runs-on: ubuntu-latest
    name: 'Trigger workflow to build services'
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: build_services

